#ifndef CHEAT_DEFINES_HPP
#define CHEAT_DEFINES_HPP

#define CHEAT_ADD_KEYS
#define CHEAT_MEGA_JUMP
#define CHEAT_ADD_HEALTH_POTIONS
#define CHEAT_ADD_MANA_POTIONS
#define CHEAT_ADD_BOMB

#endif // CHEAT_DEFINES_HPP
