#ifndef GLOBAL_BUILD_DEFINES_HPP_
#define GLOBAL_BUILD_DEFINES_HPP_

#define MAP_EDITOR_ENABLED
#define DISABLE_CAMPAIGN
#define ENABLE_CHEATS
#define INPUT_ENABLE_ALL
//#define USE_DEBUG_DEFINES

#endif
