#include "SpriteTransformPipeline.hpp"

const CDefaultSpriteTransformPipeline CDefaultSpriteTransformPipeline::INSTANCE;
const CBackgroundSpriteTransformPipeline CBackgroundSpriteTransformPipeline::INSTANCE;
